### ISSUE TITLE
incorrect legend

### ISSUE THREAD

**Issue by mizraelson** [JetBrains/lets-plot-kotlin#104]
I have plotted a deprogram by combining geomSegment() and geomPoint(). When I apply color schemes to each function, I get a joined legend which I would want to be separated. 

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/18702359/147688661-c0268dc2-c254-4ccb-a88b-8a88f12ffc7a.png">

In the picture above I want to have different legends for "sex" and "age", not joined together. 

Here is the part of code that creates a deprogram plot:

`operator fun Plot.plus(dendro: GeomDendroLayer) = run {

    this + geomSegment(dendro.edgesData) {
        x = "x1"
        y = "y1"
        xend = "x2"
        yend = "y2"
        linetype = dendro.ops.edgeLinetype
        color = dendro.ops.edgeColor
    } + geomPoint(
        dendro.pointsData
    ) {
        x = "x"
        y = "y"
        shape = dendro.ops.nodeShape
        color = dendro.ops.nodeColor
    }
}

var plot = letsPlot()
        plot += geomDendro(tree, connectionType = ConnectionType.rectangle, edgeMetaInheritance = EdgeMetaInheritance.up){
            nodeColor = "age"
            edgeColor = "sex"
        }
`

**Comment by alshan** [comment]
Hi, there can not be >1 legends for a single aesthetic (i.e. "color"). In the case of segments and points the workaround would be to use the "fill" aesthetic for the points layer. 
For that to work you will need to use a 'fillable' shape for points, like shape 19 or 21.

![image](https://user-images.githubusercontent.com/4430922/147696225-1cca1f2f-a9ac-490b-9cc8-07fe8a7b1c76.png)

**Comment by mizraelson** [comment]
I tried that, but I get a weird result:
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/18702359/147698757-09c33b3d-a8c5-4ea2-8289-3edcdeff5e11.png">

`operator fun Plot.plus(dendro: GeomDendroLayer) = run {

    this +
            geomSegment(dendro.edgesData) {
        x = "x1"
        y = "y1"
        xend = "x2"
        yend = "y2"
        linetype = dendro.ops.edgeLinetype
        color = dendro.ops.edgeColor
    }+
            geomPoint(
        dendro.pointsData, shape = 19
    ) {
        x = "x"
        y = "y"
        fill = dendro.ops.nodeColor
    }
}`

**Comment by alshan** [comment]
Oh, sorry, shape 19 wont work, try shape 21.

**Comment by mizraelson** [comment]
> Oh, sorry, shape 19 wont work, try shape 21.

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/18702359/147701461-ae03e0f0-12fb-430b-9def-fb9ab74f9f00.png">

Is there a way to use the same color for a counter or make it blank so its a solid circle?

**Comment by alshan** [comment]
Transparent color = "rgba(0, 0, 0, 0)" might work.
May be size = 0 also but not sure.

**Comment by alshan** [comment]
UPD: 
- support for multiple color scales was aded in [v 4.3.0](https://github.com/JetBrains/lets-plot-kotlin/blob/master/CHANGELOG.md#430---2023-03-09) - see aesthetics `paint_a, paint_b, paint_c`.
- the `stroke` aesthetic was added in [v 4.4.0](https://github.com/JetBrains/lets-plot-kotlin/blob/master/CHANGELOG.md#440---2023-05-10) and provide grater control over points border.
