### ISSUE TITLE
How to make geomImage display 2d array?

### ISSUE THREAD

**Issue by koodzi** [JetBrains/lets-plot-kotlin#106]
Is it possible to use `geomImag` like in this examples?
https://nbviewer.org/github/JetBrains/lets-plot-docs/blob/master/source/examples/cookbook/image_101.ipynb

**Comment by alshan** [comment]
We haven't added `geomImage` to the Kotlin API yet.
Perhaps we should do it.

Currently you can try to use [geomRaster](https://lets-plot.org/kotlin/plot-api/jetbrains.letsPlot.geom/geom-raster/geom-raster.html)  (see an example in its Python' counterpart [geom_raster](https://lets-plot.org/pages/api/lets_plot.geom_raster.html#lets_plot.geom_raster)).
It doesn't work with 2d arrays though.

**Comment by alshan** [comment]
Hi @koodzi ! What data-structure(s) would be preferable for storing a grayscale (2D) or color (RGB(A) - 3D) image data?
Do you read images from files (png, tif, DEM-files) or generate them?

**Comment by alshan** [comment]
`geomImage()` added in [v4.2.0](https://github.com/JetBrains/lets-plot-kotlin/releases/tag/v4.2.0)

See demos: 
[image_101](https://nbviewer.jupyter.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.2.0/image_101.ipynb),
[image_fisher_boat](https://nbviewer.jupyter.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.2.0/image_fisher_boat.ipynb),
[image_grayscale](https://nbviewer.jupyter.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.2.0/image_grayscale.ipynb),
[image_extent](https://nbviewer.jupyter.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.2.0/image_extent.ipynb)
