### ISSUE TITLE
Creating a custom palette

### ISSUE THREAD

**Issue by Kernald** [JetBrains/lets-plot-kotlin#128]
ggplot seems to have a (convoluted...) way to define custom palettes (e.g. [here](https://www.jumpingrivers.com/blog/custom-colour-palettes-for-ggplot2/)). As far as I understand, there's no similar facility exposed in Let's Plot?

**Comment by alshan** [comment]
Hi @Kernald, 
There are [`scaleColorGradientN()`](https://lets-plot.org/kotlin/-lets--plot--kotlin/org.jetbrains.letsPlot.scale/scale-color-gradient-n.html), [`scaleFillGradientN()`](https://lets-plot.org/kotlin/-lets--plot--kotlin/org.jetbrains.letsPlot.scale/scale-fill-gradient-n.html) 
functions where you can use a custom color palette to create continuous or discrete color scale.

[`scaleColorManual()`](https://lets-plot.org/kotlin/-lets--plot--kotlin/org.jetbrains.letsPlot.scale/scale-color-manual.html), [`scaleFillManual()`](https://lets-plot.org/kotlin/-lets--plot--kotlin/org.jetbrains.letsPlot.scale/scale-fill-manual.html) are also can be used for this purpose but rather for discrete scales.

**Comment by Kernald** [comment]
Thanks, that's exactly what I was looking for! Sorry for the noise :-)
