### ISSUE TITLE
Vulnerability in lets-plot-batik:2.5.0

### ISSUE THREAD

**Issue by ubertrombone** [JetBrains/lets-plot-kotlin#140]
IntelliJ is providing the following warning in build.gradle.kts: "Provides transitive vulnerable dependency org.apache.xmlgraphics:batik-bridge:1.15". 

The issue links here: https://github.com/advisories/GHSA-r29w-r9ph-vm76

**Comment by alshan** [comment]
Related: https://github.com/JetBrains/lets-plot/issues/624

**Comment by alshan** [comment]
Fixed in [v4.2.0](https://github.com/JetBrains/lets-plot-kotlin/releases/tag/v4.2.0)
