### ISSUE TITLE
Boxplot bug

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#143]
Why are some strange outliers drawn here? Is this a bug?
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/49092338/203947423-4a784650-2542-4a66-a0ab-b9ef986d0419.png">

**Comment by alshan** [comment]
This half-bug possibly) By the internal convention, outlier points are data-points where `y` aes is "defined" i.e. not `NaN` or `null`.
Try to add `"y" to listOf(null,null,null)` to your dataset and to the mapping.
