### ISSUE TITLE
Plot not displaying in SwingNode

### ISSUE THREAD

**Issue by dosier** [JetBrains/lets-plot-kotlin#152]
I am trying to display a plot in a JavaFX application. My idea was to nest a JPanel inside a SwingNode and add this to a JavaFX node.
I have adapted the example shown here:
https://github.com/JetBrains/lets-plot-kotlin/blob/master/demo/jvm-javafx/src/main/kotlin/minimalDemo/Main.kt

My current solution is: 
```kt
fun createSwingNode(offers: List<MarketOffer.Floor>): SwingNode {
    val plots = createPlots(offers)
    val selectedPlotKey = plots.keys.first()
    val controller = Controller(
        plots,
        selectedPlotKey,
        false
    )
    val swingNode = SwingNode()
    SwingUtilities.invokeLater {
        swingNode.content = controller.createPlotPanel()
    }
    return swingNode
}
```

Which I then use as follows:
```kt
vbox.replaceChildren(Label("Loading historical data for ${order.name}..."))
scope.launch {
    val offers = order.getOfferHistory().sortedBy { it.time }
    withContext(Dispatchers.JavaFx) {
        vbox.replaceChildren(createSwingNode(offers))
```

However, nothing shows up. Am I missing something here?

**Comment by alshan** [comment]
Hi @dosier , 
I've just added a minimal example of Lets-Plot in JavaFX application. It is stripped off version of other minimal demos: 

https://github.com/alshan/lets-plot-mini-apps/tree/main/jvm-javafx-app

The app works fine. Try to work up from here by adding controls and so on to figure out at what point it stops working.
