### ISSUE TITLE
scaleColorGradient2 doesn't work

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#153]
`scaleColorGradient2 ` ignores its first argument.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/49092338/220348372-abac633c-eaa9-4852-a1c9-852a19302d43.png">
<img width="647" alt="image" src="https://user-images.githubusercontent.com/49092338/220348441-44f79d26-703f-4615-b36b-e4fc0c8d99f7.png">

**Comment by alshan** [comment]
The "gradient 2" scales work according to the ggplot2 specifications: [scale_gradient](https://ggplot2.tidyverse.org/reference/scale_gradient.html)

In your example you'll have to adjust the "midpoint":

> The midpoint (in data value) of the diverging scale. Defaults to 0.

Alternatively, you may want to use `scaleColorGradientN()` which will compute the midpoint itself.
