### ISSUE TITLE
Is it possible to set axis limits?

### ISSUE THREAD

**Issue by Tamada4a** [JetBrains/lets-plot-kotlin#170]
Hello everyone Is it possible in lets-plot to shift the boundaries of the graph so that they are at the origin? What do I mean:
From this
![image](https://user-images.githubusercontent.com/99251317/229279899-4662845b-799d-43e6-887c-1644fe66957e.png)
To this
![image](https://user-images.githubusercontent.com/99251317/229279897-c9bf27d7-9ae5-4663-9d6c-d070e4e8238f.png)

**Comment by alshan** [comment]
Hi, try to use `scaleXContinuous(expand = listOf(0, 0))`.

**Comment by Tamada4a** [comment]
Thanks!
