### ISSUE TITLE
Skip name in the legend

### ISSUE THREAD

**Issue by Tamada4a** [JetBrains/lets-plot-kotlin#171]
is it possible to hide a certain element in the legend?
For example, from this
![Графическая оценка НКФ](https://user-images.githubusercontent.com/99251317/230127417-d8d81313-a80a-40b8-9ac9-9719c1f777f6.png)
to this
![image](https://user-images.githubusercontent.com/99251317/230127531-49a115c7-efa2-4970-9016-38c7b194672a.png)

**Comment by alshan** [comment]
If you define color as a constant (i.e. via the "color" parameter in `geomHLine()`) then it wont show up in legend.

Alternatively, you can try to limit "breaks" on the color scale : `scaleColorDiscrete(breaks=listOf(.. data values .. ))`

**Comment by Tamada4a** [comment]
Thanks a lot!!
