### ISSUE TITLE
How to remove side tooltips without `anchor`?

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#189]
Is it possible to get rid of side tooltips while keeping main tooltips the dynamic position of the main tooltips?
<img width="160" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/20123613-95f7-4066-8e7b-0e406b857ce0">

**Comment by AndreiKingsley** [comment]
For example, I want to display layerTooltips with 1 line and remove side tooltips here:
<img width="1068" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/f055b6a5-8bb6-41df-80ed-bc65a2f0d16b">

**Comment by AndreiKingsley** [comment]
Perhaps we should separate the side and axis tooltips into a separate API? Because the side tooltips formatting thing in `layerTooltips()` is not obvious at all. And also here we could hide side tooltips.

**Comment by alshan** [comment]
In v4.4.2 see new option `disableSplitting()` in tooltip customization API: https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.4.2/tooltips_disable_splitting.ipynb
