### ISSUE TITLE
Subplot themes not inherited by parent

### ISSUE THREAD

**Issue by Martmists-GH** [JetBrains/lets-plot-kotlin#197]
The following two plots have been set to use the Darcula theme:
![Screenshot_20230802_180208](https://github.com/JetBrains/lets-plot-kotlin/assets/16361449/153c03f1-e795-4b73-aff6-c223a4a0d65d)

However, There is still spacing and a border in white. This cannot currently be solved as SubPlotsFeature does not support themeing.

Code:
```kotlin
// Subplot 1
val freq = letsPlot(mapOf(
    "frequency" to fftData.indices,
    "gain (dB)" to fftData.map(Complex::length),
)) + geomLine() {
    x = "frequency"
    y = "gain (dB)"
} + scaleXLog10() + scaleYLog10()
// Subplot 2
val phase = letsPlot(mapOf(
    "frequency" to fftData.indices,
    "phase (rad)" to fftData.map(Complex::angle),
)) + geomLine {
    x = "frequency"
    y = "phase (rad)"
} + scaleXLog10()
// Parent plot
val grid = gggrid(
    plots=listOf(freq, phase).map { it + flavorDarcula() },  // Apply theme
    ncol = 1,
)  // + flavorDarcula()  // Unsupported
grid.show()
```

**Comment by alshan** [comment]
Fixed in v4.5.0: [Common Theme for Subplots](https://github.com/JetBrains/lets-plot-kotlin#common-theme-for-subplots).
However, inheritance works other way around: elements inherit theme of their container.
