### ISSUE TITLE
Changing a default color palette

### ISSUE THREAD

**Issue by tklinchik** [JetBrains/lets-plot-kotlin#213]
Is there a way to change default color palette to apply to all plots?
I've looked through many examples and couldn't find the way to update the default.

**Comment by alshan** [comment]
The default color palette is not configurable at the moment. Could be a good featue.

**Comment by tklinchik** [comment]
Agree. Is there a way to apply color palette such as `Set2` to a single plot?

**Comment by alshan** [comment]
Absolutely, try to use [`scaleColorBrewer()`](https://lets-plot.org/kotlin/-lets--plot--kotlin/org.jetbrains.letsPlot.scale/scale-color-brewer.html) / [`scaleFillBrewer()`](https://lets-plot.org/kotlin/-lets--plot--kotlin/org.jetbrains.letsPlot.scale/scale-fill-brewer.html) with your plot.

**Comment by alshan** [comment]
No follow ups
