### ISSUE TITLE
How to plot dots with hex colors?

### ISSUE THREAD

**Issue by Kyant0** [JetBrains/lets-plot-kotlin#215]
It seems using the hex value as color is incorrect.
![image](https://github.com/JetBrains/lets-plot-kotlin/assets/76829190/eb40c717-c10c-4ff3-804d-3ba0be46afe2)

**Comment by Kyant0** [comment]
https://datalore.jetbrains.com/notebook/TDFXxJPhrAGax2aJqKiYc3/IAP5ItFdVr0xziTyFhZHoP

**Comment by IKupriyanov-HORIS** [comment]
Hi!
I think the `geomImshow()` function might fit your needs much better, than `geomPoint()`.   
See demos:
[image_101.ipynb](https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.2.0/image_101.ipynb)
[image_fisher_boat.ipynb](https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.2.0/image_fisher_boat.ipynb)
[image_extent.ipynb](https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.2.0/image_extent.ipynb)
[image_grayscale.ipynb](https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.2.0/image_grayscale.ipynb)

**Comment by Kyant0** [comment]
Thanks, that's what I want
