### ISSUE TITLE
Axis scales are not automatically configured when using `geomABLine()`

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#218]
<img width="686" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/d3f7d454-744a-46de-8a19-95a0098de3aa">

**Comment by alshan** [comment]
This is expected behavior due to boundless nature of this geom.
See geom_abline details:  https://ggplot2.tidyverse.org/reference/geom_abline.html#details

**Comment by devcrocod** [comment]
Can abLine be an independent plot?
I mean a real use case, where `abLine`is used without being tied to other plots (their scales)

**Comment by alshan** [comment]
Sure but in this case you will specify the geometry bounds explicitly via limits.
