### ISSUE TITLE
y scale doesn't work for bars/area

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#219]
<img width="685" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/c6325e81-c575-4f53-9bba-8624ee79f41a">

**Comment by IKupriyanov-HORIS** [comment]
Hello, @AndreiKingsley. What specific result were you expecting? This is how ggplot2 works:
![image](https://github.com/JetBrains/lets-plot-kotlin/assets/14200189/6bc111ea-6aa3-499f-a3a9-0cc62d8f5a79)

**Comment by AndreiKingsley** [comment]
I expect that if I set axes limits, the plot will have axes exactly what I set - that's for certain.
Regarding the behavior of bars in ggplot - why can't they be cropped?

**Comment by alshan** [comment]
Fixed by https://github.com/JetBrains/lets-plot/commit/d435488f5b1390632c08abd7c6d10c5700715dee
Note however that the proper way to do zooming is to use xlim, ylim in coord system.
