### ISSUE TITLE
Improve border line type experience

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#220]
Now it looks awful
<img width="731" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/8ead5eb8-97e8-4116-adc5-2ceff90bca89">
![image](https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/f9223b43-1dce-41c7-85b6-eba82ed139fa)

**Comment by alshan** [comment]
Dotted lines look as expected , why?

**Comment by devcrocod** [comment]
When the line type is dotted, I expect to see the original line through the dots. In this case, it is not so. 
Especially, you can see this on the last box with whiskers.

**Comment by alshan** [comment]
No, in ggplot "dotted" line consists of dots with the background in between. Take a look: http://www.cookbook-r.com/Graphs/Shapes_and_line_types/

To achieve visual effect that you needed try to combine two layers of boxes: dotted lines on top of solid lines.

**Comment by IKupriyanov-HORIS** [comment]
ggplot2 output for reference:
![image](https://github.com/JetBrains/lets-plot-kotlin/assets/14200189/11a99751-932d-4be0-9722-4fbfd242d10c)

**Comment by devcrocod** [comment]
Okay, I was talking about understanding.
Here I have highlighted the problem areas:
<img width="260" alt="Screenshot 2023-11-10 at 14 21 16" src="https://github.com/JetBrains/lets-plot-kotlin/assets/19648120/d94d87a6-88bf-40d5-984e-7f48ab331e86">

Even the ggplot examples given here look cleaner

**Comment by alshan** [comment]
@IKupriyanov-HORIS Looks like ggplot adjusts dots size/distance to the line width.

**Comment by alshan** [comment]
Was fixed in 4.7.3
