### ISSUE TITLE
How to hide only main tooltip (not side one)?

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#232]
For example, here, I want to hide main tooltips, anв still have the sides:
<img width="809" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/3f4e2bc8-c5e1-44e2-90de-95dddecbdab7">

**Comment by alshan** [comment]
Try `tooltips = layerTooltips(*emptyArray())`

**Comment by AndreiKingsley** [comment]
<img width="798" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/864146e2-c38b-4ac2-8446-86c1ff90417e">
Doesn't work

**Comment by OLarionova-HORIS** [comment]
The point is to hide the main tooltip but keep the axis tooltip, right?  
Unfortunately, there is no such mechanism in the current version.

By the way, `disableSplitting()` does not affect axis tooltips. It moves "side tooltips" to the main tooltip, and by "side tooltips" we mean positional tooltips such as boxplot has.

**Comment by AndreiKingsley** [comment]
OK, but I think that would be a useful feature

**Comment by OLarionova-HORIS** [comment]
The next release will add the ability to hide the general tooltip (without hiding the axis tooltips) using 
`theme(tooltip = "blank")`.

**Comment by OLarionova-HORIS** [comment]
Fixed in [LPK v4.7.0](https://github.com/JetBrains/lets-plot-kotlin/blob/master/CHANGELOG.md#470---2024-03-15)
