### ISSUE TITLE
Make middle strip in `geomCrossbar()` optional

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#233]
This is a fairly common usecase , i.e. the user needs the bars themselves, without the middle bar. That is, I'd like to propose the following behavior: if `y` is not assigned, the bar is not drawn (as it is currently when passing a list of nulls).
Actual:
<img width="728" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/1a1303d3-e487-4271-8f72-9d1860cc6fa1">
Expected:
<img width="743" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/8de9c94f-6536-493e-a88a-69fdbce8881e">

We did already the same for boxplot: #143

**Comment by alshan** [comment]
Hi, try using `fatten = 0`

**Comment by AndreiKingsley** [comment]
Ok, but let's get rid of middle bars on 0, why not?

**Comment by alshan** [comment]
0 is a legit value.

**Comment by AndreiKingsley** [comment]
I mean if y is not assigned, don't draw a middle bar at all instead od drawn it at 0

**Comment by alshan** [comment]
Got it.

**Comment by alshan** [comment]
Fixed by commit: https://github.com/JetBrains/lets-plot/commit/8a554dc7c8d5b1d0d8456299608d53bae4266a54
