### ISSUE TITLE
Add `linetype` parameter in `elementLine()` and `elementRect()`

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#235]
Add `linetype` for theme elements with behaviour similar to `linetypes` in geoms.

**Comment by alshan** [comment]
What `linetype` would do for `elementText()` ?

**Comment by AndreiKingsley** [comment]
I apologise, of course I meant `elementLine()`.

**Comment by OLarionova-HORIS** [comment]
Added via commit: https://github.com/JetBrains/lets-plot/commit/c0b386fe1771e6acc28e8ca9e57854b482984184

**Comment by alshan** [comment]
See: [example notebook](https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.7.1/theme_linetype.ipynb).
