### ISSUE TITLE
Make middle strip in `geomBoxplot()` optional

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#236]
As in #233, there're use cases when middle strip is not needed. The most obvious one is a candlestick chart:
<img width="831" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/ddee3a8e-2828-40c6-9c34-5c61ce650f7f">

So, expected behaviour: when `middle` is not assigned, the middle strip is not drawn (as it is now when you assign a list of null to it.).

**Comment by alshan** [comment]
I believe it should work for box-plot in current lets-plot.

**Comment by AndreiKingsley** [comment]
Oh, really. Thanks!
