### ISSUE TITLE
Q: any way to line-wrap facet labels?

### ISSUE THREAD

**Issue by tecunningham** [JetBrains/lets-plot-kotlin#237]
My facet labels don't seem to contain line breaks (I tried newlines or HTML breaks.).

GGplot supports `label_wrap_gen`, is there any workaround in lets-plot?

**Comment by OLarionova-HORIS** [comment]
Unfortunately, at the moment there is no way to create a multi-line facet labels. But it is in the plans.

**Comment by OLarionova-HORIS** [comment]
Added via commit: https://github.com/JetBrains/lets-plot/commit/5236da54af75539743abfea9df051687c1fbe6c7

**Comment by alshan** [comment]
A workaround was added in v4.7.1, see: [example notebook](https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.7.1/facet_multiline_titles.ipynb).
