### ISSUE TITLE
`linetype` doesn't work for `geomTile`

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot-kotlin#241]
<img width="881" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/20ad3ebf-4d92-4347-8115-c2ae66af2fb9">
<img width="812" alt="image" src="https://github.com/JetBrains/lets-plot-kotlin/assets/49092338/f6b8e863-ae82-475b-a322-d89bf3dd0e01">

**Comment by alshan** [comment]
Fixed in v4.7.2
