### ISSUE TITLE
Add Installation Section to README.md

### ISSUE THREAD

**Issue by nort3x** [JetBrains/lets-plot-kotlin#250]
This library explains everything for consumers who use KotlinNotebook alongside it,
but there is no section in `README.md` about including this into an existing kotlin project  using gradle/maven

this can be done by manually finding packages on mavenCentral but regarding users of this library are mostly scientific community they are not very familiar with this ( you might argue that then they would definitely not using this without notebook, but still it's hard for them to figure this out when they need it)

please provide a section in `readme` on how to import this into gradle/maven projects for better DX

thank you

**Comment by alshan** [comment]
Hi, to find information on configuring Lets-Plot dependencies in a Gradle project, scroll through the README past the "Quickstart" section and click on the "Usage | JVM and Kotlin/JS" link here: https://github.com/JetBrains/lets-plot-kotlin/blob/master/README.md#table-of-contents

Following this link, you will find all the necessary information, including snippets of the Gradle build file: https://github.com/JetBrains/lets-plot-kotlin/blob/master/USAGE_BATIK_JFX_JS.md#jvm-swing-batik

You will also find a link to the "mini apps" demo project, which contains examples of Gradle build files: https://github.com/alshan/lets-plot-mini-apps/blob/main/jvm-swing-batik-app/build.gradle.kts

At the moment, I'm not sure what exactly can be improved here. Suggestions?

**Comment by nort3x** [comment]
Hi alshan,
thank you it was hidden in plain sight, my bad 😄
