### ISSUE TITLE
Facet grid truncated in jupyter

### ISSUE THREAD

**Issue by patonw** [JetBrains/lets-plot-kotlin#28]
Playing around with the mtcars dataset, un-faceted plots are displayed correctly in jupyter via the kotlin-jupyter kernel:
![2020-07-04-153159_745x489_scrot](https://user-images.githubusercontent.com/1527962/86521935-9a3f9f80-be0b-11ea-8694-8318ab4d1ffc.png)

When trying to facet by cylinder or any integer column, the image is truncated to varying degrees based on my window size. Regardless, part of the data, axes or guide is always missing:

![2020-07-04-153222_735x381_scrot](https://user-images.githubusercontent.com/1527962/86522052-2c947300-be0d-11ea-9715-78011f34afd7.png)

![2020-07-04-153844_1085x480_scrot](https://user-images.githubusercontent.com/1527962/86522057-3322ea80-be0d-11ea-8c98-4b31a7280fe5.png)

![2020-07-04-154313_925x682_scrot](https://user-images.githubusercontent.com/1527962/86522061-374f0800-be0d-11ea-8368-0b29d8ea0f24.png)

Notebook code for reference:
```
%use lets-plot, kotlin-statistics

@file:Repository("https://jitpack.io")
@file:DependsOn("de.mpicbg.scicomp:krangl:0.11")

import krangl.*

val df = DataFrame.readCSV("data/mtcars.csv")

fun DataCol.toList() = when (this) {
    is DoubleCol -> asDoubles()
    is IntCol -> asInts()
    is LongCol -> asLongs()
    is StringCol -> asStrings()
    else -> null
}?.toList()

fun DataFrame.toMap() = this.cols
    .map { it.name to it.toList() }
    .filter { it.second != null }
    .toMap()

df["cyl"].asInts().toSet()

val plot = lets_plot(df.toMap()){x = "disp"; y = "hp" }

(
    lets_plot(df.toMap()){x = "disp"; y = "hp" }
        + geom_point() { size="mpg"; color = "cyl"}
        + scale_color_continuous("red", "blue", guide = guide_legend(ncol=1))
        + facet_grid("cyl")
)

(
    ggplot(df.toMap()){x = "disp"}
        + geom_histogram()
        + facet_grid("gear", "cyl")
)
```

**Comment by alshan** [comment]
I can suggest using `ggsize(w,h)` function to adjust the overall plot size like: `lets_plot(..) + ggsize(500, 200)`.

**Comment by alshan** [comment]
Would be nice to limit the plot size to the available client width.

**Comment by alshan** [comment]
In v1.3.0 the output should not exceed width of the container element (unless the plot size is overridden by the `ggsize()` function).
Please checkout [v1.3.0](https://github.com/JetBrains/lets-plot-kotlin/releases/tag/v1.3.0).
