### ISSUE TITLE
Fix geom_bin2d doc

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot-kotlin#36]
The current one was copied from geom_histogram:
Displays a 1d distribution by dividing variable mapped to x axis into bins and counting the number of observations in each bin.

**Comment by MKoroteev-HORIS** [comment]
This comment was actually copied from lets-plot where it is also incorrect. Fixed in https://github.com/JetBrains/lets-plot-kotlin/commit/80178c9b27086b38216de57cbbbbf7e0bc5bd466.
