### ISSUE TITLE
Nice to have an interactive zooming / panning on plots.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot-kotlin#38]
See discussion: https://github.com/JetBrains/lets-plot-kotlin/issues/37#issuecomment-688295606

**Comment by boofhead** [comment]
Hi @alshan, 

has there been any progress on this feature? It looks like the functionality is there with live_maps? 
Possibly it's not suitable to be applied to the general case?

**Comment by alshan** [comment]
I'm planning this feature for Q4, is it important to you?

> Possibly it's not suitable to be applied to the general case?
Yes, that's the case.

**Comment by boofhead** [comment]
Q4 would be great! Yes for us it's a really important feature. We are in the process of relocating our researchers to the cloud and would like to do a solution using docker and JetBrains projector but properly interactive plots are essential. Lets-plot is great and pan and zoom would save us a lot of dev effort.

**Comment by alshan** [comment]
We will get to it ASAP though I've no idea what is projector.

**Comment by boofhead** [comment]
https://blog.jetbrains.com/blog/2021/03/11/projector-is-out/

**Comment by fmvin** [comment]
Vote for this issue. Please add.

**Comment by alshan** [comment]
We've been doing significant code refactorings in relation to this feature. I hope we will have some progress by the `22 end.

**Comment by hathawayj** [comment]
I love this package.  Thanks for the great work.  Checking in on the ability to zoom.

**Comment by alshan** [comment]
@hathawayj , we are gearing up for it )

**Comment by RobertM314** [comment]
Just wanted to add my desire to see zoom-able, pan-able plots added to this excellent package

**Comment by alshan** [comment]
Hi all, please try pan/zoom in [v4.9.0](https://github.com/JetBrains/lets-plot-kotlin?tab=readme-ov-file#what-is-new-in-490)!

**Comment by dgandhi1-godaddy** [comment]
@alshan 
Kotlin compose desktop it doesnt work

**Comment by alshan** [comment]
@dgandhi1-godaddy you are right, at the moment `ggtb()` only works in notebooks and in generally "web output".
We are planning to cover other envs in early 2025.

**Comment by alshan** [comment]
@BenWoodworth this is likely happening because in the latest release lets-plot switched to new integration framework with Kotlin Jupyter IDEA plugin and Swing output is now the default.
Try to execute: `letsPlotNotebookConfig.swingEnabled = false` in your notebook. This should switch the output back to html.

**Comment by BenWoodworth** [comment]
@alshan That did the trick, thank you so much! :rocket:

**Comment by madhavsinghlifespark2002** [comment]
Hi @alshan,

I want to implement a zoom-in and zoom-out feature. How can this be done in a KMM project (Desktop/Android/iOS)?

Is this feature currently available? If yes, in which version is it supported?
