### ISSUE TITLE
JavaFX demo does not compile

### ISSUE THREAD

**Issue by veyndan** [JetBrains/lets-plot-kotlin#40]
I was trying to run and compile the JavaFX `minimalDemo` (as referenced [here](https://github.com/JetBrains/lets-plot-kotlin/blob/master/README_DEV.md#an-example-of-a-minimal-jvm-based-application)) but have received a type mismatch exception.

```
e: /Users/v.stuart/IdeaProjects/lets-plot-kotlin/demo/jvm-javafx/src/main/kotlin/minimalDemo/Main.kt: (56, 69): Type mismatch: inferred type is (SvgSvgElement) -> SceneMapperJfxPanel but (SvgSvgElement) -> JComponent was expected
```

**Comment by alshan** [comment]
Are you able to build the demos using ` ./gradlew :jvm-javafx:build` command in the command line? 

IMO should not be any issues here because `SceneMapperJfxPanel` inherits `JComponent` via `javafx.embed.swing.JFXPanel`. I'm using jdk 1.8 with javafx bundled.

**Comment by veyndan** [comment]
Thanks for looking into this 😄 I had forgotten to mention that I was using OpenJDK 1.8 and was using the [OpenJFX Gradle plugin](https://openjfx.io/). The issue was to do with my JavaFX set up.

In case anyone faces the same issue, my Gradle script was originally:

```gradle
javafx {
    version = "14"
    modules = ['javafx.controls', 'javafx.graphics']
}
```

But I needed to include the `javafx.swing` module to get this to work:

```gradle
javafx {
    version = "14"
    modules = ['javafx.controls', 'javafx.graphics', 'javafx.swing']
}
```
