### ISSUE TITLE
X axis labels are not sorted alphanumerically

### ISSUE THREAD

**Issue by krzema12** [JetBrains/lets-plot-kotlin#48]
I'm trying to visualize a number of commits made per module in my single-repo project, per month. On X axis I want to have labels like `2020-04`, and Y axis should show the number of commits. My code is as follows:

```kotlin
    ...
    val plotData = mapOf (
        "yearMonth" to yearMonths,
        "module" to modules,
    )

    var plot = lets_plot(plotData) +
            geom_bar { x = "yearMonth"; fill = "module" } +
            ggsize(1920, 1080) +
            ggtitle("Number of commits per module")
```

Everything works fine, except that I'm getting such order of labels which looks totally random:

![image](https://user-images.githubusercontent.com/3110813/97846990-29dc5880-1cef-11eb-8a0f-c2a11211c94f.png)

As you can see, the order is not even alphanumeric, and I'd expect it to be so (analogy to ggplot, see e.g. https://sebastiansauer.github.io/ordering-bars/: _"And the rule is: ... if character, an alphabetical order ist used"_). My data provided in `yearMonths` is ordered the way I want (alphanumerically).

How can I control the order of the labels? I'm also curious what's the contract with lets-plot for this matter. How about sorting it alphanumerically by default, and providing a way to customize it?

I didn't manage to reproduce it on a smaller set of data.

**Comment by alshan** [comment]
Hi @krzema12 ! All the above is finally in Lets-Plot-Kotlin [v1.3.0](https://github.com/JetBrains/lets-plot-kotlin/releases/tag/v1.3.0) :)

The formatting demo is here: https://nbviewer.jupyter.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/formatting_axes_etc.ipynb

**Comment by krzema12** [comment]
Thank you @alshan for this feature!
