### ISSUE TITLE
Moving out of jcenter/bintray?

### ISSUE THREAD

**Issue by bjonnh** [JetBrains/lets-plot-kotlin#55]
Is there a plan to move this outside of Jfrog deprecated repositories?

**Comment by alshan** [comment]
Yes, we are planning the migration for early April.

**Comment by alshan** [comment]
Since [v2.0.1](https://github.com/JetBrains/lets-plot-kotlin/releases/tag/v2.0.1) all artifacts are published to Maven Central.
