### ISSUE TITLE
Viewing the plot-api documentation online

### ISSUE THREAD

**Issue by PHPirates** [JetBrains/lets-plot-kotlin#6]
When I go to https://github.com/JetBrains/lets-plot-kotlin/blob/master/docs/guide/user_guide.ipynb and click on the geom_reference link to get to the documentation, I get a 404. I don't exactly know why, the link seems to be correct (when I hover over it).
When I copy the url manually and visit https://render.githubusercontent.com/plot-api/docs/plot-api/jetbrains.lets-plot.geom/index.html then I get an 'Unknown type'.

For now I just render with htmlpreview: https://htmlpreview.github.io/?https://github.com/JetBrains/lets-plot-kotlin/blob/master/plot-api/docs/plot-api/index.html, but a proper solution would be convenient.

**Comment by alshan** [comment]
This looks like a half-baked adaptation of python lets-plot [guide](https://github.com/JetBrains/lets-plot/blob/master/docs/guide/user_guide.ipynb)

For now please try to use this one.

**Comment by alshan** [comment]
All links in user_guide.ipynb must be fine now but this notebook should be opened in nbviewer for the links to work.

Both, the guide and the reference are accessible via links in the [README](https://github.com/JetBrains/lets-plot-kotlin/blob/master/README.md#guide).

**Comment by 2x2xplz** [comment]
The API reference is not available via the [link provided in the README](https://htmlpreview.github.io/?https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/api-reference/plot-api/index.html).

`Error: Cannot load https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/plot-api/docs/plot-api/index.html: 429 Too Many Requests`

It does come up occasionally, but when trying to learn the library and 90% of requests to view the API are refused, it's rather frustrating.

**Comment by alshan** [comment]
@2x2xplz Seems like some issues with 'htmlpreview' : https://github.com/htmlpreview/htmlpreview.github.com/issues/92

**Comment by alshan** [comment]
'htmlpreview' should be working now.
