### ISSUE TITLE
Add possibility to create a pie chart, a bar chart with horizontal bars

### ISSUE THREAD

**Issue by achifal** [JetBrains/lets-plot-kotlin#68]
It would be nice to have pie chart and bar chart with horizontal bars support

**Comment by KirylBubovich** [comment]
Yay, this is a cleaner way to do this. Thanks a lot for your answers and help!
![image](https://user-images.githubusercontent.com/47569841/116000225-fd4b2e80-a5f7-11eb-9ba1-301dfc204c46.png)

**Comment by alshan** [comment]
Very cool )  Do you order slices? I've read somewhere that pie chart looks the best when the 1st biggest slice goes to the left from 12 o'clock and all other slices go clockwise in descending order:

![image](https://user-images.githubusercontent.com/4430922/116168920-900bcc00-a6d1-11eb-9c11-c0d5f9343f93.png)

**Comment by KirylBubovich** [comment]
Good concept). Now I put the slices in descending order except the last slice. The last slice is the sum of all the remaining values to ensure that only the largest X number of slices are displayed, and the rest are combined
![image](https://user-images.githubusercontent.com/47569841/116466854-af445e00-a877-11eb-8f55-64ec79bfd7ed.png)

**Comment by KirylBubovich** [comment]
In mathematics, it is possible to move from one coordinate system to another. Converting between polar and Cartesian coordinates looks like this
![image](https://user-images.githubusercontent.com/47569841/116467623-8ec8d380-a878-11eb-9536-d76aeaf9e4f5.png)
Let's say we have a semicircle. Here is an example of converting it to polar coordinates 
![polar](https://user-images.githubusercontent.com/47569841/116470334-f896ac80-a87b-11eb-82cd-eb8f8d59e585.png)
It seems like a pie chart can be built using this conversion. And when the polar coordinate system is supported, it will be easy to switch to using it. Maybe it is possible to do such an implementation for now to avoid waiting for polar coordinates support. What do you think?)

**Comment by alshan** [comment]
Would be perfect if the biggest slice was to the left of 12 o'clock ) :
![image](https://user-images.githubusercontent.com/4430922/116618497-24ae3e00-a90d-11eb-8c44-3d8ac717e329.png)

**Comment by alshan** [comment]
> In mathematics...

Exactly, this is how polar coordinate system should project X, Y etc. aesthetics to the display space. X-axis becomes a circle, bars are translated to slices and all other geometries are distorted accordingly.  
https://ggplot2.tidyverse.org/reference/coord_polar.html

**Comment by KirylBubovich** [comment]
@alshan Thanks a lot for adding coordFlip! A bar chart with horizontal bars is now possible 🎉

**Comment by alshan** [comment]
@KirylBubovich You are very welcome ) I remember about coordPolar but couldn't find a resource to work on it unfortunately.

**Comment by KirylBubovich** [comment]
No worries, thank you for being transparent. I appreciate your work and time)

**Comment by alshan** [comment]
`geomPie` added in [v4.2.0](https://github.com/JetBrains/lets-plot-kotlin/releases/tag/v4.2.0)

**Comment by achifal** [comment]
@alshan Thank you so much!
