### ISSUE TITLE
Failed to process '%use lets-plot' command. Unknown library 'lets-plot'

### ISSUE THREAD

**Issue by mrljdx** [JetBrains/lets-plot-kotlin#7]
Hi, I have this problem, but I don't know why：

![image](https://user-images.githubusercontent.com/4383863/75627869-f94b9880-5c0e-11ea-841c-c4408403881f.png)

My native python environment is：

![image](https://user-images.githubusercontent.com/4383863/75627916-5ba49900-5c0f-11ea-88a7-ea4c61c4ff90.png)

I am looking forward to your reply to help me solve this problem～

**Comment by ileasile** [comment]
Hello, mrljdx! What version of kotlin jupyter kernel do you use? Try to update to the latest one.

**Comment by mrljdx** [comment]
Hi ileasile, my kotlin jumpyter kernel is the latest one . 
![image](https://user-images.githubusercontent.com/4383863/76154632-a6944400-611a-11ea-8372-81e6b6b37b21.png)
I tried a lot of things, and finally rebooted the computer and found the problem resolved.  :joy:
![image](https://user-images.githubusercontent.com/4383863/76154695-7e591500-611b-11ea-97c1-db4bfaab7367.png)
