### ISSUE TITLE
Where is the actual documentation of the framework?

### ISSUE THREAD

**Issue by NoakPalander** [JetBrains/lets-plot-kotlin#70]
The title is rather self explanatory, where is the documentation for how to use lets-plot-kotlin? It'd be relevant to have at least _something_ that would explain how you e.g plot multiple separate lines in one plot, how you add legends, how you give them proper coloring etc. I'm not sure if it's just that lets-plot-kotlin is very primitive at this stage or what's the deal.

**Comment by alshan** [comment]
> how you e.g plot multiple separate lines in one plot, how you add legends, how you give them proper coloring etc

Such a documentation for lets-plot-kotlin doesn't exist but don't panic)  There is a fantastic book [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/index.html) explaning all the concepts using ggplot2 R-package.

Specifically:
- multiple separate lines: [4 Collective geoms](https://ggplot2-book.org/collective-geoms.html?q=group#multiple-groups-one-aesthetic)
- legends, coloring: [11 Colour scales and legends](https://ggplot2-book.org/scale-colour.html)

After you become familiar with the "grammar of graphics" idioms you can proceed to our [examples](https://github.com/JetBrains/lets-plot-kotlin/blob/master/docs/examples.md) and learn the specific of the Kotlin API.
