### ISSUE TITLE
Too limited mapping options in `GenericAesMapping`

### ISSUE THREAD

**Issue by holgerbrandl** [JetBrains/lets-plot-kotlin#82]
As of v3.01 only very few aesthetics attributes are supported in `GenericAesMapping`. Because of that many ggplot2 plots are not compatible with letsplot at the moment.

It would be nice to support more attributes such as yintercept, xintercept, size, alpha, shape, stroke, ymin,    ymax,    xend,    yend,    weight and label.

**Comment by alshan** [comment]
Many more mapping are supported by the layers themselves.
For example, you can map the size of point using mappings in the points layer:
```
p + geomPoint {size="brainwt"}
``` 
Is this what you are looking for? 

Perhaps we can extend the list of 'generic' mappings as well.

**Comment by alshan** [comment]
Fixed in [v3.2.0](https://github.com/JetBrains/lets-plot-kotlin#what-is-new-in-320)
